### ISSUE TITLE
你好，我用yolov3-tiny.cfg训练了自己的目标识别的数据，但是当我想对其进行追踪的时候，我的报错为ValueError: need at least one array to stack，是因为ckpt.t7这个权重导致只能追踪person吗？

### ISSUE THREAD

**Issue by yudadabing** [weixu000/pytorch-yolov3-deepsort#2]

**Comment by weixu000** [comment]
https://github.com/weixu000/pytorch-yolov3-deepsort/blob/cf0a68f2d74ed5a3faa68caab1749faa6422799c/yolo/detection.py#L67

这里把其他类别去掉了

**Comment by yudadabing** [comment]
Network successfully loaded
Loading weights from weights/ckpt.t7... Done!
Traceback (most recent call last):
  File "video_play.py", line 21, in <module>
    tracks = tracker.update(*detections, frame)
  File "F:\YOLOV3\detection and tracking\pytorch-yolov3-deepsort-master\sort\deep_sort.py", line 18, in update
    features = self._get_features(bbox_xyxy, ori_img)
  File "F:\YOLOV3\detection and tracking\pytorch-yolov3-deepsort-master\sort\deep_sort.py", line 35, in _get_features
    features = self.extractor(features)
  File "F:\YOLOV3\detection and tracking\pytorch-yolov3-deepsort-master\sort\deep\feature_extractor.py", line 20, in __call__
    img = np.stack([cv2.resize(cv2.cvtColor(x, cv2.COLOR_RGB2BGR), (64, 128)) for x in img]).astype(np.float32)
  File "D:\Anconda\envs\pytorch_env\lib\site-packages\numpy\core\shape_base.py", line 412, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack
您好，还是会有这个错误呀？
